// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuLE5k5jspZ8k0nzhZ9X6fSOFiTV5S7mo',
    appId: '1:833208594065:web:a6d8246d378b04c4e2d930',
    messagingSenderId: '833208594065',
    projectId: 'save-later-2245',
    authDomain: 'save-later-2245.firebaseapp.com',
    storageBucket: 'save-later-2245.firebasestorage.app',
    measurementId: 'G-1NPSLBTE86',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5Bffs7oW-gXhh4cKJFQnha3LV-yA59WM',
    appId: '1:833208594065:android:b3e2a32a9db58f14e2d930',
    messagingSenderId: '833208594065',
    projectId: 'save-later-2245',
    storageBucket: 'save-later-2245.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLj8uTKy7qVgIBxFPOsA2PI-8buEjhRnc',
    appId: '1:833208594065:ios:2624178f9ff9dc9de2d930',
    messagingSenderId: '833208594065',
    projectId: 'save-later-2245',
    storageBucket: 'save-later-2245.firebasestorage.app',
    iosBundleId: 'com.savelater.saveLater',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLj8uTKy7qVgIBxFPOsA2PI-8buEjhRnc',
    appId: '1:833208594065:ios:2624178f9ff9dc9de2d930',
    messagingSenderId: '833208594065',
    projectId: 'save-later-2245',
    storageBucket: 'save-later-2245.firebasestorage.app',
    iosBundleId: 'com.savelater.saveLater',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuLE5k5jspZ8k0nzhZ9X6fSOFiTV5S7mo',
    appId: '1:833208594065:web:9c9f228bce1217e7e2d930',
    messagingSenderId: '833208594065',
    projectId: 'save-later-2245',
    authDomain: 'save-later-2245.firebaseapp.com',
    storageBucket: 'save-later-2245.firebasestorage.app',
    measurementId: 'G-HT9WLR2HPR',
  );
}
